### ISSUE TITLE
android手机威信小程序生成二维码乱码

### ISSUE THREAD

**Issue by XiFanYin** [q310550690/uni-app-qrcode#1]
uni-app使用该库生成的二维码，编译成的微信小程序代码，在android手机微信小程序中生成的二维码乱码，同样的在ios手机微信小程序中生成的二维码就没有就没有问题！请问这是什么原因？是代码问题？还是在编译过程中出现的问题？

**Comment by q310550690** [comment]
小程序canvas回传有延时，更新到0.0.9就行
